Les 10
Angular-OTUS/ToDoList-VyacheslavRomashov pull request #2
Opened 2023-10-12 17:08 UTC by romashovv

2023-11-07 18:38 UTC, nlapshin requested changes

2023-11-07 18:38 UTC, nlapshin commented on src/app/components/todo-list/todo-list.component.ts
> +  }
Почему бы эту логику не вынести в сервис по управлению списка todoList?

2023-11-07 18:38 UTC, nlapshin commented on src/app/components/todo-list/todo-list.component.ts
> +    })
Попробуйте соеденить apiService, todoService, toastService, чтобы бизнес логика была в todoService.

2023-11-28 14:47 UTC, viktor-berezin approved these changes

2023-11-28 14:47 UTC, merged